spring:
  jwt:
    secretKey: 12345678910987654321ABCDEFFEDCBA01234567899876543210ABCDEFFEDCBA
    tokenLifespan: 432000000   # 120 hours = 5 days #
    refreshTokenLifespan: 864000000    # 240 hours = 10 days #
  account:
    admin:
      username: Admin
      password: Admin@123
      email: admin@gmail.com
      firstname: admin
      lastname: istrator
  role_admin:
    id: 1
    name: ADMIN
  role_user:
    id: 2
    name: USER